# Generated by Django 5.2.13 on 2026-05-20 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="temporary",
        ),
    ]
