version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: postgres_vector
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ai_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    networks:
      - ai_network
    depends_on:
      - db

  minio:
    image: minio/minio:RELEASE.2024-01-28T22-35-53Z
    container_name: minio_s3
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - ai_network

  redis:
      image: redis:7
      container_name: redis
      ports:
        - "6379:6379"
      networks:
        - ai_network

  django:
    build: ./PrivateAi
    container_name: django_service
    env_file:
      - .env
    volumes:
      - ./PrivateAi:/app
      - shared_data:/app/shared
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
      - redis
      - minio
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ai_network

networks:
  ai_network:
    driver: bridge

volumes:
  postgres_data:
  shared_data:
  minio_data: